services:
  - type: web
    name: documaker-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /app/backend/static/uploads
      sizeGB: 1
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: documaker-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

  - type: static
    name: documaker-frontend
    buildCommand: npm ci --prefix frontend && npm run build --prefix frontend
    publishPath: frontend/dist
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE
        fromService:
          name: documaker-backend
          type: web
          property: url

databases:
  - name: documaker-db
    plan: starter
