"""sync_user_profile_models

Revision ID: 2c51599e6a82
Revises: 736e42b0192f
Create Date: 2025-08-23 11:18:43.630391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2c51599e6a82"
down_revision: Union[str, None] = "736e42b0192f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_profile_experiences_display_order"), table_name="profile_experiences"
    )
    op.drop_index(
        op.f("ix_profile_experiences_user_profile_id"), table_name="profile_experiences"
    )
    op.drop_column("user_profiles", "certificates")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column(
            "certificates",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_profile_experiences_user_profile_id"),
        "profile_experiences",
        ["user_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_profile_experiences_display_order"),
        "profile_experiences",
        ["user_profile_id", "display_order"],
        unique=False,
    )
    # ### end Alembic commands ###
