"""Add JSON fields for skills certifications education to UserProfile

Revision ID: c81ca3584abe
Revises: 2c51599e6a82
Create Date: 2025-08-23 17:20:16.131592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c81ca3584abe"
down_revision: Union[str, None] = "2c51599e6a82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
